project_root: "D:/04_TRADING_SMALLCAPS"
reports_dir: "D:/04_TRADING_SMALLCAPS/reports/audits"

universe:
  market_cap_max: 2000000000
  float_max: 100000000
  price_min: 0.5
  price_max: 20.0
  volume_min: 500000
  pct_chg_min: 0.15
  exchanges: ["NASDAQ","NYSE","NYSE MKT","AMEX"]
